[package]
name = "femboyware_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.49"
quote = "1.0.23"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
syn = "1.0.107"
